variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  image:
    name: "carlonluca/qt-dev:5.15.2"
    entrypoint: [""]
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j16
  artifacts:
    paths:
      - build/HelloWorld
    expire_in: 1 week


test_job:
  stage: test
  script:
    - echo "here you run tests"

deploy_job:
  stage: deploy
  script:
    - echo "deploy your executable"
  dependencies:
    - build_job
