variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test_qt5

Test_qt5:
  stage: test_qt5
  image:
    name: "carlonluca/qt-dev:5.15.2"
    entrypoint: [""]
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j16
   # - ./HelloWorld
